### ISSUE TITLE
student main page 구현

### ISSUE THREAD

**Issue by jianchoi02** [JustOneBite/job-front#17]
**Description**
- 학생 로그인 후 Home을 클릭했을 때 mainpage 구현하기

**Todo**
- [ ] mainPage navigation bar 제작
- [ ] 학습 type 별 학습하기, 목록보기 버튼 만들기
- [ ] 각 학습 별 성취율 표시
- [ ] 학습 여부 표시 
- [ ] 학습하기 클릭 시 해당 학습 사이트로 넘어가게 하기

**ETC**
- 디자인은 기능 구현 후 제작
