### ISSUE TITLE
학생 메인 페이지 제작

### ISSUE THREAD

**Issue by jonghyun03** [JustOneBite/job-front#19]
**Description**
- 학생 페이지의 홈 화면을 구성

**Todo**
- [ ] 메인페이지 브랜치 생성
- [ ] mainPage 폴더 생성
- [ ] mainPage/page.js 구성
- [ ] mainPage/page.module.css 구성
- [ ] 실행

**ETC**
- details
