### ISSUE TITLE
로그인 페이지 구현 및 실행

### ISSUE THREAD

**Issue by daejun4582** [JustOneBite/job-front#2]
**Description**
- 백과 로그인 및 토큰 생성 및 관리 확인

**Todo**
- [x] 학생 login - jwt 구현
- [x] 학생 register 구현
- [x] 선생님 login - session 구현
- [x] 선생님 register 구현

**ETC**
- details
