### ISSUE TITLE
학생 고객센터 게시판 구현 완성 

### ISSUE THREAD

**Issue by dbwoflaqnzo3** [JustOneBite/job-front#20]
**Description**
- 고객센터 CRUD완성 
- fetch나 이런거는 로컬 서버로 해서 테스트 완료 
- DB연결이나 fetch 경로는 벡과의 합의를 통해 수정할 예정 
- 구체적인 CSS틀은 잡아놓았으나 수치는 Fix해야함 
- 필터는 카테고리나 기능 구현같은게 합의가 되면 진행할 예정 

**Todo**
- [ ] studentService > {edit>{form.js , page.js} , write>{page.js}}추가
- [ ] studentService폴더 아래엔 {filter.js , listItem.js , page.js}추가
- [ ] styles폴더를 student app폴더에 삽입하고 그 안에 {sSlistItem.module,studentService.module,studentSVEdit.module,studentSVWrite.module}.css 파일 추가 후 각각 연결함 
- [ ] 추가적으로 테스트를 위해 Nav바 임시로 만들어 놓음 ( layout.js안에 , layout.module.css 추가 

**ETC**
- app폴더 밖에 테스트 한답치고 pages>posts 폴더를 만들고 안에 서버기능을 대충 리시브만 하게 만들어 놓았는데 참고
