### ISSUE TITLE
student writing page 구현

### ISSUE THREAD

**Issue by jianchoi02** [JustOneBite/job-front#3]
**Description**
- 학생 writing page를 구현하기

**Todo**
- [x] writing 주제, 단어 수, 제출 횟수 받아오는 함수 구현
- [x] 학생이 작성한 글 api 통해서 완성도 테스트 구현
- [x] 작성한 글 선생님에게 보내는 함수 구현
- [x] 문법 오류인 내용 화면 오른쪽에 표시하기
